### ISSUE TITLE
Amplify

### ISSUE THREAD

**Issue by nekooooo0203** [nekooooo0203/ChatApp#249]
https://aws.amazon.com/jp/getting-started/hands-on/build-flutter-app-amplify/
https://qiita.com/makishy/items/e93a057c6ad3614f87b6

**Comment by nekooooo0203** [comment]
Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

**Comment by nekooooo0203** [comment]
https://github.com/aws-amplify/amplify-flutter/commit/809d80d4da6fb100ac726810203f9c1796d3e65a
Refactor amplify_core to amplify_flutter (#273)

**Comment by nekooooo0203** [comment]
https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-user-attributes

**Comment by nekooooo0203** [comment]
https://serverless-stack.com/chapters/create-a-cognito-user-pool.html

**Comment by nekooooo0203** [comment]
amplify_core, amplify_auth_cognito : 0.0.1-dev.3
E/amplify:flutter:auth_cognito(17124): AMPLIFY_FETCH_SESSION_FAILED
E/amplify:flutter:auth_cognito(17124): AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(17124): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareSessionResult(AuthCognito.kt:523)
E/amplify:flutter:auth_cognito(17124): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:372)
E/amplify:flutter:auth_cognito(17124): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$onFetchAuthSession$1.accept(AuthCognito.kt:76)
E/amplify:flutter:auth_cognito(17124): 	at com.amplifyframework.auth.cognito.MobileClientSessionAdapter.fetchSignedOutSession(MobileClientSessionAdapter.java:66)
E/amplify:flutter:auth_cognito(17124): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$7.onResult(AWSCognitoAuthPlugin.java:484)
E/amplify:flutter:auth_cognito(17124): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$7.onResult(AWSCognitoAuthPlugin.java:478)
E/amplify:flutter:auth_cognito(17124): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
E/amplify:flutter:auth_cognito(17124): 	at java.lang.Thread.run(Thread.java:923)

**Comment by nekooooo0203** [comment]
amplify_core, amplify_auth_cognito : 0.0.1-dev.6
```
D/AWSMobileClient(17268): waitForSignIn: userState:SIGNED_OUT
W/AWSMobileClient(17268): getCredentials: Failed to getCredentials from Cognito Identity
W/AWSMobileClient(17268): com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 31577b54-3bce-4fb7-bdf3-09804b08de35)
W/AWSMobileClient(17268): 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
W/AWSMobileClient(17268): 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
W/AWSMobileClient(17268): 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/AWSMobileClient(17268): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1728)
W/AWSMobileClient(17268): 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
W/AWSMobileClient(17268): 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
W/AWSMobileClient(17268): 	at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3898)
W/AWSMobileClient(17268): 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
W/AWSMobileClient(17268): 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
W/AWSMobileClient(17268): 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
W/AWSMobileClient(17268): 	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:369)
W/AWSMobileClient(17268): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:414)
W/AWSMobileClient(17268): 	at com.amazonaws.mobile.client.AWSMobileClient$1.run(AWSMobileClient.java:411)
W/AWSMobileClient(17268): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
W/AWSMobileClient(17268): 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by nekooooo0203** [comment]
https://www.youtube.com/watch?v=x8xEkNCd3Vg

**Comment by nekooooo0203** [comment]
https://github.com/aws-amplify/amplify-flutter/issues/274

**Comment by nekooooo0203** [comment]
https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter

**Comment by nekooooo0203** [comment]
https://www.r3it.com/blog/aws-amplify-admin-ui-202012
https://sandbox.amplifyapp.com/getting-started

**Comment by nekooooo0203** [comment]
https://sandbox.amplifyapp.com/
Data:
AWS AppSync
Amazon DynamoDB

**Comment by nekooooo0203** [comment]
Firestore  VS  Amplify datastore

**Comment by nekooooo0203** [comment]
**Firestore VS Amplify datastore : security**

**Comment by nekooooo0203** [comment]
Firestore VS Amplify datastore : security

**Comment by nekooooo0203** [comment]
**Firestore VS Amplify datastore : auth**
**Firebase Authentication**


**Cognito**

**Comment by nekooooo0203** [comment]
**Firestore  VS  Amplify datastore  :  query**
get,
list : get documents
create
update, set
delete

query
where
array contains
order by

**Comment by nekooooo0203** [comment]
**AWS Amplify CLIの使い方〜インストールから初期セットアップまで〜Amplify-CLIコマンド一覧**
https://qiita.com/Junpei_Takagi/items/f2bc567761880471fd54#amplify-cli%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E4%B8%80%E8%A6%A7
